### ISSUE TITLE
[statsig] improve evaluation context to statsig user conversion

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/go-sdk-contrib#519]
### Overview

The Statsig provider [converts](https://github.com/open-feature/go-sdk-contrib/blob/main/providers/statsig/pkg/provider.go#L391) [evaluation context](https://openfeature.dev/specification/sections/evaluation-context) to a [Statsig user](https://docs.statsig.com/server/golangSDK#statsig-user). However, it only supports directly mapping properties to what has been defined by a Statsig user. This makes interoperability impossible for providers that require a `targetKey`.

### Proposal

```[tasklist]
### Tasks
- [ ] Map `targetingKey` to `UserID` if `UserID` is not set on the evaluation context
- [ ] Return a `NewTargetingKeyMissingResolutionError` if `UserID` is not defined on the Statsig user after the conversion.
- [ ] Map non-matching evaluation context properties under `Custom`
```

### Resources

- https://docs.statsig.com/server/concepts/user#why-is-statsiguser-with-a-userid-required-for-server-sdks

**Comment by beeme1mr** [comment]
FYI @liran2000

**Comment by liran2000** [comment]
Yeah, it was [done](https://github.com/open-feature/go-sdk-contrib/blob/main/providers/statsig/pkg/provider.go#L391) in [Java provider](https://github.com/open-feature/java-sdk-contrib/blob/main/providers/statsig/src/main/java/dev/openfeature/contrib/providers/statsig/ContextTransformer.java#L33), seems missing here.

**Comment by liran2000** [comment]
@beeme1mr can be resolved, via #520.
